version : "3"

services :
  app :
    build : 
      context : ""
      args : 
        - ENVIRONMENT = local


    ports :
      - "8080:8080"
    entrypoint : ["uvicorn", "app.main:app","--host", "0.0.0.0", "--port", "8080","--reload"]
    
# this maps external storage ressorces to places in our docker container   
    volumes : 
      - ./app:/usr/src/app

  app-test :

    build : 
      context : ""
      args : 
        - ENVIRONMENT = test
    volumes : 
      - .:/usr/src
#    entypoint : ["pipenv", "run", "pytest", "tests"]

  # postgresdb:
  #   image : postgres:14.1-alpine
  #   ports : 
  #     - "5432:5432"
  #   environment :
  #     - POSTGRES_USER
  #     - POSTGRES_PASSWORD
  #     - POSTGRES_DB


